### ISSUE TITLE
如何能保证登录一次后，一天都都免登陆

### ISSUE THREAD

**Issue by row-column** [alexxiyang/shiro-redis#100]
目前如下配置：
 
    <bean id="redisManager" class="org.crazycake.shiro.RedisManager">
        <property name="host" value="${redis.host}"/>
        <property name="password" value="${redis.password}"/>
        <property name="timeout" value="10000"/>
    </bean>
    

    
    <bean id="redisSessionDAO" class="org.crazycake.shiro.RedisSessionDAO">
        <property name="expire" value="-1"/>
        <property name="sessionInMemoryEnabled" value="true"/>
        <property name="sessionInMemoryTimeout" value="10000"/>
        <property name="redisManager" ref="redisManager"/>
    </bean>
    <bean id="sessionManager" class="org.apache.shiro.web.session.mgt.DefaultWebSessionManager">
        <property name="sessionDAO" ref="redisSessionDAO"/>
    </bean>
    

    
    
    <bean id="cacheManager" class="org.crazycake.shiro.RedisCacheManager">
        <property name="redisManager" ref="redisManager"/>
    </bean>
    

    
    <bean id="myRealm" class="com.galaxy.common.shiro.ShiroDbRealm"/>

    
    <bean id="securityManager" class="org.apache.shiro.web.mgt.DefaultWebSecurityManager">
        <property name="sessionManager" ref="sessionManager"/>
        <property name="cacheManager" ref="cacheManager"/>
        <property name="realm" ref="myRealm"/>
        <property name="rememberMeManager.cipherKey" value="kPH+bIxk5D2deZiIxcaaaA=="/>
    </bean>

    <bean class="org.springframework.aop.framework.autoproxy.DefaultAdvisorAutoProxyCreator"></bean>

    <bean class="org.apache.shiro.spring.security.interceptor.AuthorizationAttributeSourceAdvisor">
        <property name="securityManager" ref="securityManager"></property>
    </bean>

    
    <bean id="lifecycleBeanPostProcessor" class="org.apache.shiro.spring.LifecycleBeanPostProcessor"/>

但发现 30分钟后，刷新页面后还需要重新登录，请问如何能解决我的需求，非常感谢回复

**Comment by ivanvera** [comment]
sessionManager.setGlobalSessionTimeout(86400000);

redisSessionDAO.setExpire(86400000);

这两个地方需要设置
