### ISSUE TITLE
Secure Redis using "rediss" protocol. 

### ISSUE THREAD

**Issue by OltaSema** [alexxiyang/shiro-redis#101]
Hi,
it seems like there is no way to connect to redis using "rediss" protocol. How do you specify this attribute?

**Comment by vnicers** [comment]
RedisManager redisManager = new RedisManager();
        JedisPool jedisPool = new JedisPool(new JedisPoolConfig(),
                redisConfig.getHost(),
                redisConfig.getPort(),
                redisConfig.getTimeout(),
                redisConfig.getPassword(),
                redisConfig.getDatabase(),
                redisConfig.useSsl()
        );

        redisManager.setJedisPool(jedisPool);

it's ok for me
