### ISSUE TITLE
是否能支持 spring-boot-starter-data-redis?

### ISSUE THREAD

**Issue by Ahaochan** [alexxiyang/shiro-redis#103]
我尝试提供了一个基于`spring-boot-starter-data-redis`的[RedisTemplateManager](https://github.com/Ahaochan/project/blob/master/ahao-spring-boot-shiro/src/main/java/com/ahao/spring/boot/redis/RedisTemplateManager.java)

但是有一个问题. `shiro-redis`的`jdk`版本为`1.6`, 不支持`Spring Boot 2.x`, 请问是出于什么考虑将`jdk`版本压在`1.6`.
如果允许的话, 我可以发一个PR.

**Comment by alexxiyang** [comment]
没有什么考虑，就是很久没更新了，在3.3.0中，已经jdk已经升级为11
