### ISSUE TITLE
如何主动过期数据

### ISSUE THREAD

**Issue by aeroyu** [alexxiyang/shiro-redis#110]
场景是如果一个用户被注销，通过更改数据库状态后，需要过期该已登陆的用户

**Comment by manondidi** [comment]
用shiro logout 就把redis中的 token删掉了
不需要直接操作redis,shiro-redis只是提供了redis持久化而已,
这种业务相关的应该直接操作 shiro

**Comment by manondidi** [comment]
aeroyu 你这个issue可以close了

但是,作者这么好的项目,为什么不继续维护啊,
issue没回复,代码也没更新了
很多人都把你这套东西弄到生产环境了
希望你继续维护

**Comment by aeroyu** [comment]
`RealmSecurityManager rsm = (RealmSecurityManager) SecurityUtils.getSecurityManager();
CustomRealm shiroRealm = (CustomRealm) rsm.getRealms().iterator().next();
shiroRealm.clearUserCachedAuthorizationInfo(userId);`

我是这样解决的

**Comment by manondidi** [comment]
issues 可以close了

**Comment by manondidi** [comment]
clearUserCachedAuthorizationInfo 你这个方法应该不是自带的吧
怎么实现的

**Comment by manondidi** [comment]
```
    public void clearAuthorization() {
        this.getAuthenticationCache().clear();
    }

    public void removeUserSession(String userId) {
        Collection<Session> sessions = redisSessionDAO.getActiveSessions();
        for (Session session : sessions) {
            Object obj = session.getAttribute(DefaultSubjectContext.PRINCIPALS_SESSION_KEY);
            if (obj instanceof SimplePrincipalCollection) {
                SimplePrincipalCollection spc = (SimplePrincipalCollection) obj;
                if (userId.equals(spc.getPrimaryPrincipal())) {
                    redisSessionDAO.delete(session);
                }
            }

        }
    }


    /**
     * shiro刷新所有人权限
     */
    public static void reloadAuthorizing() {
        RealmSecurityManager rsm = (RealmSecurityManager) SecurityUtils.getSecurityManager();
        MyShiroRealm realm = (MyShiroRealm) rsm.getRealms().iterator().next();
        realm.clearAuthorization();
    }

    /**
     * shiro清除该用户所有token 用于修改密码后过期该用户所有token
     */
    public static void removeUser(String userId) {
        RealmSecurityManager rsm = (RealmSecurityManager) SecurityUtils.getSecurityManager();
        MyShiroRealm realm = (MyShiroRealm) rsm.getRealms().iterator().next();
        realm.removeUserSession(userId);

    }
```
我是这么处理的 删除用户的token不能用clearcache 因为 clearcache并不会让token实效,只有在调用login的时候会重新访问数据库

**Comment by aeroyu** [comment]
> clearUserCachedAuthorizationInfo 你这个方法应该不是自带的吧
> 怎么实现的

private void clearUserCachedAuthorizationInfo(Integer userId) {
        RealmSecurityManager rsm = (RealmSecurityManager) SecurityUtils.getSecurityManager();
        CustomRealm shiroRealm = (CustomRealm) rsm.getRealms().iterator().next();
        shiroRealm.clearUserCachedAuthorizationInfo(userId);
    }

**Comment by manondidi** [comment]
shiroRealm.clearUserCachedAuthorizationInfo(userId);
这个方法应该也是你自己写的吧, 你这种方式能删除redis中的session吗
你只是取消了用户的授权,没删除他的认证啊 ,你这个方法调用之后 redis中的数据有减少吗

**Comment by manondidi** [comment]
你这种写法 redis中的session有变少吗

**Comment by manondidi** [comment]
我这里有两个方法,
1.删除某个用户所有token
2.清楚所有用户的认证信息
我这里 用sessionId作为token,每次请求接口都在header中带上来, session设置过期时间是七天
也就是说七天之内,用户有带上来这个token,都会自动再续期七天.
1.用户某个用户修改密码, 之前保存在redis的那些session(token)都要通通失效了
2.当我编辑权限或者角色的时候,我要刷新所有用户的权限,,让他们 访问接口上 @RequiresPermissions
的方法的时候必须重新走一遍 doGetAuthorizationInfo() 方法 而不从缓存中取他的认证信息


但是我看你在过期session的时候用到了clearCache方法,这个方法只会删除缓存中的,并不会删除redis中的数据, 除非该用户再次调用SecurityUtils.getSubject().login()方法,否则是不会重走doGetAuthenticationInfo( )这个方法的

**Comment by aeroyu** [comment]
> 我这里有两个方法,
> 1.删除某个用户所有token
> 2.清楚所有用户的认证信息
> 我这里 用sessionId作为token,每次请求接口都在header中带上来, session设置过期时间是七天
> 也就是说七天之内,用户有带上来这个token,都会自动再续期七天.
> 1.用户某个用户修改密码, 之前保存在redis的那些session(token)都要通通失效了
> 2.当我编辑权限或者角色的时候,我要刷新所有用户的权限,,让他们 访问接口上 @RequiresPermissions
> 的方法的时候必须重新走一遍 doGetAuthorizationInfo() 方法 而不从缓存中取他的认证信息
> 
> 但是我看你在过期session的时候用到了clearCache方法,这个方法只会删除缓存中的,并不会删除redis中的数据, 除非该用户再次调用SecurityUtils.getSubject().login()方法,否则是不会重走doGetAuthenticationInfo( )这个方法的



> ```
> package com.example.demo.config.shiro;
> 
> import com.example.demo.dao.UserRepository;
> import com.example.demo.pojo.po.Permission;
> import com.example.demo.pojo.po.Role;
> import com.example.demo.pojo.po.User;
> import com.example.demo.service.UserService;
> import lombok.Data;
> import lombok.extern.slf4j.Slf4j;
> import org.apache.shiro.SecurityUtils;
> import org.apache.shiro.authc.*;
> import org.apache.shiro.authz.AuthorizationInfo;
> import org.apache.shiro.authz.SimpleAuthorizationInfo;
> import org.apache.shiro.mgt.RealmSecurityManager;
> import org.apache.shiro.realm.AuthorizingRealm;
> import org.apache.shiro.session.Session;
> import org.apache.shiro.session.mgt.SessionManager;
> import org.apache.shiro.subject.PrincipalCollection;
> import org.apache.shiro.subject.SimplePrincipalCollection;
> import org.apache.shiro.subject.support.DefaultSubjectContext;
> import org.crazycake.shiro.RedisSessionDAO;
> import org.springframework.beans.factory.annotation.Autowired;
> 
> import java.text.SimpleDateFormat;
> import java.util.*;
> 
> @Slf4j
> @Data
> public class MyShiroRealm extends AuthorizingRealm {
>     @Autowired
>     private UserRepository userRepository;
>     @Autowired
>     RedisSessionDAO redisSessionDAO;
> 
>     @Override
>     protected AuthorizationInfo doGetAuthorizationInfo(PrincipalCollection principalCollection) {
>         SimpleAuthorizationInfo authorizationInfo = new SimpleAuthorizationInfo();
>         String userIdStr = (String) principalCollection.getPrimaryPrincipal();
>         User userPo = userRepository.findById(Long.parseLong(userIdStr)).get();
>         for (Role role : userPo.getRoleList()) {
>             authorizationInfo.addRole(role.getName());
>             for (Permission p : role.getPermissions()) {
>                 authorizationInfo.addStringPermission(p.getPermission());
>             }
>         }
>         return authorizationInfo;
>     }
> 
>     @Override
>     protected AuthenticationInfo doGetAuthenticationInfo(AuthenticationToken authenticationToken) throws AuthenticationException {
>         String user = (String) authenticationToken.getPrincipal();
>         String password = new String((char[]) authenticationToken.getCredentials());
>         User userPo = userRepository.findUserByUserNameOrMailOrTel(user, user, user);
>         if (userPo == null || !userPo.getPassword().equals(password)) {
>             throw new AccountException("用户名或密码错误");
>         }
>         if (Optional.ofNullable(userPo.getBanTime()).orElse(new Date(0)).after(new Date())) {
>             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
>             throw new DisabledAccountException(String.format("该用户因{%s}被封停至{%s}", userPo.getBanReason(), sdf.format(userPo.getBanTime())));
>         }
>         return new SimpleAuthenticationInfo(userPo.getId().toString(), userPo.getPassword(), getName());
>     }
> 
>     /**
>      * 删除所有人的授权cache 使其再走一次doGetAuthorizationInfo
>      */
> 
>     public void clearAuthorization() {
>         this.getAuthorizationCache().clear();
>     }
> 
>     public void removeUserSession(String userId) {
>         redisSessionDAO.getActiveSessions().stream()
>                 .filter(session -> {
>                     return session.getAttribute(DefaultSubjectContext.PRINCIPALS_SESSION_KEY) instanceof SimplePrincipalCollection
>                             &&
>                             userId.equals(((SimplePrincipalCollection) session.getAttribute(DefaultSubjectContext.PRINCIPALS_SESSION_KEY)).getPrimaryPrincipal());
>                 }).forEach(redisSessionDAO::delete);
>     }
> 
> 
>     /**
>      * shiro刷新所有人权限
>      */
>     public static void reloadAuthorizing() {
>         RealmSecurityManager rsm = (RealmSecurityManager) SecurityUtils.getSecurityManager();
>         MyShiroRealm realm = (MyShiroRealm) rsm.getRealms().iterator().next();
>         realm.clearAuthorization();
>     }
> 
>     /**
>      * shiro清除该用户所有token 用于修改密码后过期该用户所有token
>      */
>     public static void removeUser(String userId) {
>         RealmSecurityManager rsm = (RealmSecurityManager) SecurityUtils.getSecurityManager();
>         MyShiroRealm realm = (MyShiroRealm) rsm.getRealms().iterator().next();
>         realm.removeUserSession(userId);
> 
>     }
> }
> ```
> 
> 我是这么处理的 删除用户的token不能用clearcache 因为 clearcache并不会让token实效,只有在调用login的时候会重新访问数据库

removeUserSession这个方法会报错
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'java.lang.String redis.clients.jedis.ScanResult.getStringCursor()'
