### ISSUE TITLE
springBoot2.2依赖方法名变更

### ISSUE THREAD

**Issue by yythlj** [alexxiyang/shiro-redis#127]
WorkAloneRedisManager.java:149的方法java.lang.String redis.clients.jedis.ScanResult.getStringCursor()在springBoot2.2的依赖的redis里没有了，由新方法java.lang.String redis.clients.jedis.ScanResult.getCursor()代替，希望作者可以更新下支持

**Comment by ETouchs** [comment]
作者似乎不维护了，可以看看以前的issue
#113

**Comment by yiyingcanfeng** [comment]
还有2个解决方法：
1. 在dependencies同级下加上:
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.9.0</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```
2. 在properties节点下加上<jedis.version>2.9.0</jedis.version>, 比如：
```xml
<properties>
    <java.version>11</java.version>
    <jedis.version>2.9.0</jedis.version>
</properties>
```
这样就可以锁定jedis的版本了

**Comment by alexxiyang** [comment]
更新成新版本了，改成了`getCursor`
