### ISSUE TITLE
JedisPool优化问题

### ISSUE THREAD

**Issue by xiyoumaila** [alexxiyang/shiro-redis#128]
JedisPool是一个成员变量，可否优化成静态变量，单例模式下只初始化一次

**Comment by alexxiyang** [comment]
很惊讶现在还有人用这个组件。我已经很久没维护这个组件了。这下我又有斗志了。🤩

**Comment by alexxiyang** [comment]
jedisPool 已经是单例模式了，并且使用了双重检查，只会初始化一次。
