### ISSUE TITLE
分布式系统中的使用问题

### ISSUE THREAD

**Issue by fwrq41251** [alexxiyang/shiro-redis#13]
manager用ConcurrentMap来管理所有的cache,在分布式系统中,怎么保证两个节点上的ConcurrentMap是同步的?

**Comment by wjw465150** [comment]
分布式系统,如果是多个独立的系统就需要多个独立的Redis Server!如果是采用SSO认证的系统,使用shiro针对SSO的配置,后台就一个Redis Server!

**Comment by wjw465150** [comment]
如果是多个独立的系统就只需要一个的Redis Server!那么在shiro的配置文件里,把redisManager.rootKey设置成不一样就可以了!具体参见readme!

**Comment by afredlyj** [comment]
我也想问这个问题。

**Comment by liaozhongqiang** [comment]
不用考虑这个，只要保证 prefix是一致就OK
