### ISSUE TITLE
目前发现复制代码中的RedisSessionDao代码自己重写，加入日志代码，发现通过同一个sessionId从ThreadLocal当中获取的session不一致

### ISSUE THREAD

**Issue by yarcl** [alexxiyang/shiro-redis#130]
有两张图片，一张是重写的大佬的代码，加了日志，一张是打印的日志。

**Comment by yarcl** [comment]
![1](https://user-images.githubusercontent.com/19200047/88471710-d368bc80-cf3e-11ea-96d8-d608ab904cba.jpg) 这个是加日志改写的dai'ma代码
![2](https://user-images.githubusercontent.com/19200047/88471712-d4015300-cf3e-11ea-89f7-a13b5a28fd3b.jpg) 这个是打印的日志
@alexxiyang 请大佬帮忙看一下，谢谢

**Comment by yarcl** [comment]
这块应该是应用了ThreadLocal的一个bug，大家看到可以升级一下版本，目前我用的版本是3.1.0的版本。或者自己修改源码解决这个问题

**Comment by RongXiong2016** [comment]
看日志像是往session不断追加属性吧
