### ISSUE TITLE
3.3.0最低支持jdk11了？ 可否打个jdk7+的版本？新特性都没用到呢，为啥要支持这么高

### ISSUE THREAD

**Issue by ilaotan** [alexxiyang/shiro-redis#132]
rt

**Comment by ilaotan** [comment]
内存泄漏这个坑，老项目要升级啊，jdk能不动就不想动

**Comment by ilaotan** [comment]
只有单元测试里用了lambda表达式，测试了下，打包完全可以用jdk7打。

**Comment by ilaotan** [comment]
算了，我自己打私服吧

**Comment by ilaotan** [comment]
更新下，老项目使用3.3.0启动不起来，使用3.2.3可以。 控制台没任何日志。 经简单分析，发现3.3.0依赖了一堆plugins，去掉后正常

**Comment by alexxiyang** [comment]
没问题，我会发布一个java8版本

**Comment by alexxiyang** [comment]
去掉了什么依赖？

**Comment by alexxiyang** [comment]
3.3.1基于java8。已经发布了，请测试

**Comment by ilaotan** [comment]
@alexxiyang   依赖了plugins ，传递了大量依赖过来。。。
`
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-checkstyle-plugin</artifactId>
			<version>3.1.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-source-plugin</artifactId>
			<version>3.2.1</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-javadoc-plugin</artifactId>
			<version>3.2.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.22.0</version>
			<scope>runtime</scope>
		</dependency>`
