### ISSUE TITLE
springboot 2.3.4 + shiro 1.6 升级3.3.0后跑不起来了,3.2.3正常运行

### ISSUE THREAD

**Issue by yuxicun** [alexxiyang/shiro-redis#134]
springboot 2.3.4 + shiro 1.6 升级3.3.0后跑不起来了,3.2.3正常运行
![image](https://user-images.githubusercontent.com/18489852/93963849-c88ca580-fd90-11ea-892e-9d0363bc710c.png)

**Comment by yuxicun** [comment]
而且似乎3.3.0 增加了一大堆插件依赖

**Comment by yuxicun** [comment]
是不是通过java11 编译的,在java8上无法运行了

**Comment by alexxiyang** [comment]
是的。非常抱歉，我会发布一个java8版本

**Comment by alexxiyang** [comment]
3.3.1已经发布，3.3.1基于java8。请测试使用3.3.1
