### ISSUE TITLE
Are you sure your framework work  as your purpose?

### ISSUE THREAD

**Issue by deposit-world** [alexxiyang/shiro-redis#16]
The method `readSession`of the `SessionDAO`has  one paramter named `sessionId`,when use Shiro in web environment ,then instance of WebSubject init in AbstractShiroFilter like this :
`return new WebSubject.Builder(getSecurityManager(), request, response).buildWebSubject();,`
but i can't find Shiro init `sessionId`at anywhere,it's mean your framework no ability to bind the `Session`that in `Redis`to current `WebSubject`. so when you inovke the method `getSession()` of `Subject`,Shiro will create new `Session`for you.
My Email : fanzhengou@aliyun.com

**Comment by alexxiyang** [comment]
Please upgrade to 2.4.8 and try again
