### ISSUE TITLE
序列化问题

### ISSUE THREAD

**Issue by huangguan18** [alexxiyang/shiro-redis#18]
请问大家是否有遇到SimpleSession的反序列化问题？session里边放置了一个整数。
虽然可以序列化，但是不能正常的反序列化，请问大家谁遇到了

**Comment by 1543453892** [comment]
我也遇到这个问题了...

**Comment by cranehe** [comment]
不知道现在这个问题解决了没有？

**Comment by sd1990** [comment]
SimpleSession内部的attribute是transient，无法序列化的

**Comment by Liesport758** [comment]
大家解决了没

**Comment by alexxiyang** [comment]
2.4.6解决了反序列化的问题
