### ISSUE TITLE
Clear cache would clear all session data from redis, too?

### ISSUE THREAD

**Issue by peter-fu** [alexxiyang/shiro-redis#2]
Hi Alex,

I think this line would clear all redis data (including session data) when cache is cleared by shire cache management, which is not expected.
https://github.com/alexxiyang/shiro-redis/blame/master/src/main/java/org/crazycake/shiro/RedisCache.java#L132

I didn't verify it, but it doesn't look correct to me.

Thanks,
Peter

**Comment by DR-YangLong** [comment]
it clear session in redis by sessionId,see the source 

private byte[] getByteKey(Serializable sessionId){
		String preKey = this.keyPrefix + sessionId;
		return preKey.getBytes();
	}

when invoke cache method,the key in redis where generated by sessionId.

**Comment by peter-fu** [comment]
我们说的也许不是一个地方。

[RedisCache](https://github.com/alexxiyang/shiro-redis/blob/be8e64b8d96ea6086a367da5d512f0bc86a97c34/src/main/java/org/crazycake/shiro/RedisCache.java#L132)中的`cache.flushDB()`里面会调用[RedisManager](https://github.com/alexxiyang/shiro-redis/blob/master/src/main/java/org/crazycake/shiro/RedisManager.java#L119)里面的`jedis.flushDB`。

**Comment by seven7ma** [comment]
解决了吗,我也在面临这个问题的困扰

**Comment by peter-fu** [comment]
这样改了一下clear()方法

![qq20170410-181303](https://cloud.githubusercontent.com/assets/930535/24857061/813db7aa-1e19-11e7-86d6-1803403c0829.png)

**Comment by alexxiyang** [comment]
@peter-fu 已根据你的代码修改了RedisCache，非常感谢你的建议。请升级至2.4.8
