### ISSUE TITLE
Will this work correctly if RedisSessionDAO is not set

### ISSUE THREAD

**Issue by harshmehta5** [alexxiyang/shiro-redis#22]
Will this work correctly if RedisSessionDAO is not used, just the RedisManager and RedisCacheManager are initialized and set as the cache manager for shiro ?

**Comment by Acvrock** [comment]
If you do not use RedisSessionDAO, Sessions to Redis can not be saved

**Comment by harshmehta5** [comment]
I only want to cache the roles and permissions of the user as I have disabled shiro session management.

**Comment by alexxiyang** [comment]
Yes, you don't need to assign sessionDAO
```INI
sessionManager = org.apache.shiro.web.session.mgt.DefaultWebSessionManager
# sessionManager.sessionDAO = $redisSessionDAO
securityManager.sessionManager = $sessionManager
```
