### ISSUE TITLE
Spring+Hibernate ,logout 后org.apache.shiro.session.UnknownSessionException: There is no session with id

### ISSUE THREAD

**Issue by MingjieLee** [alexxiyang/shiro-redis#23]
项目中的hibernate配置OpenSessionInViewFilter后，shiro logout后，会出现org.apache.shiro.session.UnknownSessionException: There is no session with id，因为session已经被删除了，找不到对应的session，可以考虑，delete()时不把session删除，只清空session中的对应数据

**Comment by alexxiyang** [comment]
不建议这样做，毕竟很多用户不适用hibernate。建议catch住这个exception然后进行容错处理
