### ISSUE TITLE
增加redis的database配置

### ISSUE THREAD

**Issue by qixiaobo** [alexxiyang/shiro-redis#25]
目前并没有redis的database配置
`/**
	 * 初始化方法
	 */
	public void init(){
		if(jedisPool == null){
			if(password != null && !"".equals(password)){
				jedisPool = new JedisPool(new JedisPoolConfig(), host, port, timeout, password);
			}else if(timeout != 0){
				jedisPool = new JedisPool(new JedisPoolConfig(), host, port,timeout);
			}else{
				jedisPool = new JedisPool(new JedisPoolConfig(), host, port);
			}
			
		}
	}`

**Comment by yanlichong** [comment]
重写了init方法可以实现

**Comment by alexxiyang** [comment]
2.4.6已经合并了可以选择database的改动
