### ISSUE TITLE
redis集群

### ISSUE THREAD

**Issue by patientmingming** [alexxiyang/shiro-redis#29]
redis目前部署的是集群，3个节点，  3个不同的端口
 RedisManager redisManager = new RedisManager();
        redisManager.setHost(host);
        redisManager.setPort(port);
        redisManager.setExpire(1800);// 配置缓存过期时间
        redisManager.setTimeout(timeout);

这个地方的host和port如何配置呢，谢谢

**Comment by teemoer** [comment]
看了下他的源码  是不支持集群的  自己clone代码下来 改成集群的就 ok了  我正在改  改好了 @ 你

**Comment by hanbing** [comment]
@teemoer  升级好吗，可以分享一下吗

**Comment by xchendeveloper** [comment]
@hanbing 最近在研究redis集群，刚提交了一个更新上来，自测可用。https://github.com/xchendeveloper/shiro-redis

**Comment by hipzhang** [comment]
传来了PrincipalCollection对象，但是这里面返回授权的key只是这种形式shiro:cache:shiro#Authorization:com.thorgene.common.shiro.UsernamePasswordRealm_0
导致，登录不同的账号，授权信息只缓存到了第一个登录的账号

`	private Object getRedisKeyFromPrincipalCollection(PrincipalCollection key) {
        Object redisKey;
		List<String> realmNames = getRealmNames(key);
		Collections.sort(realmNames);
        redisKey = joinRealmNames(realmNames);
        return redisKey;
    }`

**Comment by alexxiyang** [comment]
3.0.0支持redis集群
