### ISSUE TITLE
session.getAttribute("residentLogin")是null，但是redis里已经保存了？

### ISSUE THREAD

**Issue by VanXD** [alexxiyang/shiro-redis#30]
"\xac\xed\x00\x05sr\x00*org.apache.shiro.session.mgt.SimpleSession\x9d\x1c\xa1\xb8\xd5\x8cbn\x03\x00\x00xpw\x02\x00\xdbt\x00$abe11d9f-a0e1-494e-963d-14b677928b83sr\x00\x0ejava.util.Datehj\x81\x01KYt\x19\x03\x00\x00xpw\b\x00\x00\x01_\xa5.+\xdaxsq\x00~\x00\x03w\b\x00\x00\x01_\xa5./mxw\x13\x00\x00\x00\x00\x00\x1bw@\x00\t127.0.0.1sr\x00\x11java.util.HashMap\x05\a\xda\xc1\xc3\x16`\xd1\x03\x00\x02F\x00\nloadFactorI\x00\tthresholdxp?@\x00\x00\x00\x00\x00\x01w\b\x00\x00\x00\x02\x00\x00\x00\x02t\x00\bdeviceIdt\x00\x0f357612081944192t\x00\r**residentLogin**sr\x00/com.lansent.howjoy.domain.func.bo.ResidentLoginC\x99\x96\xf7\xee\x8a\xf9\xd6\x02\x00\x13L\x00\tcheckFlagt\x00\x13Ljava/lang/Integer;L\x00\x0censureAmountt\x00\x12Ljava/lang/String;L\x00\rheaderImagUrlq\x00~\x00\rL\x00\thouseCodeq\x00~\x00\rL\x00\x02idq\x00~\x00\rL\x00\x0eidentificationq\x00~\x00\rL\x00\x0eisImRegisteredq\x00~\x00\x0cL\x00\x12lastLoginEquipmentq\x00~\x00\x0cL\x00\x0bloginNumberq\x00~\x00\rL\x00\nloginTokenq\x00~\x00\rL\x00\x04moodq\x00~\x00\rL\x00\x0bnewDeviceIdq\x00~\x00\rL\x00\bnicknameq\x00~\x00\rL\x00\bpasswordq\x00~\x00\rL\x00\x0cregisterDatet\x00\x10Ljava/util/Date;L\x00\x0cresidentNameq\x00~\x00\rL\x00\nresidentidq\x00~\x00\x0cL\x00\x06typeIdq\x00~\x00\x0cL\x00\tvalidFlagq\x00~\x00\x0cxr\x00\"com.lansent.howjoy.domain.BasePage\xa2\x93\xa7\x9d\x10='\xa5\x02\x00\x04I\x00\x04pageI\x00\bpageSizeL\x00\x11baseBlockCodeListt\x00\x10Ljava/util/List;L\x00\x0borderFiledsq\x00~\x00\rxp\x00\x00\x00\x00\x00\x00\x00\x00sr\x00\x13java.util.ArrayListx\x81\xd2\x1d\x99\xc7a\x9d\x03\x00\x01I\x00\x04sizexp\x00\x00\x00\x01w\x04\x00\x00\x00\x01t\x00\n1101050002xpsr\x00\x11java.lang.Integer\x12\xe2\xa0\xa4\xf7\x81\x878\x02\x00\x01I\x00\x05valuexr\x00\x10java.lang.Number\x86\xac\x95\x1d\x0b\x94\xe0\x8b\x02\x00\x00xp\x00\x00\x00\x00t\x00 4e2dd20c3367fba2984741fee20c490bppt\x00 5cbfa2f1993bed71e050a10a7e1c785ct\x00\x1213062119720917661Xsq\x00~\x00\x15\x00\x00\x00\x01sq\x00~\x00\x15\x00\x00\x00\x02t\x00\x0b13681378388t\x00\x0f357612081944192ppt\x00\x0b136****8388t\x00 E10ADC3949BA59ABBE56E057F20F883Esq\x00~\x00\x03w\b\x00\x00\x01_lF\x1b\x89xt\x00\t\xe9\xad\x8f\xe8\x90\xa5\xe6\x94\xbfsq\x00~\x00\x15\a\xefN\x84q\x00~\x00\x1bq\x00~\x00\x1bxx"

这是redis中存储的结果，但是我java里取出来是null？
这个问题并不总是发生，30分钟左右出现一次。

**Comment by alexxiyang** [comment]
请升级至最新版本
