### ISSUE TITLE
开启授权缓存，发现只缓存了一条

### ISSUE THREAD

**Issue by hipzhang** [alexxiyang/shiro-redis#40]
你重写了RedisCache类，调用了getRedisKeyFromPrincipalCollection方法，传来了PrincipalCollection对象，但是这里面返回授权的key只是这种形式shiro:cache:shiro#Authorization:com.thorgene.common.shiro.UsernamePasswordRealm_0
导致，登录不同的账号，授权信息只缓存到了第一个登录的账号

`
private Object getRedisKeyFromPrincipalCollection(PrincipalCollection key) {
Object redisKey;
List realmNames = getRealmNames(key);
Collections.sort(realmNames);
redisKey = joinRealmNames(realmNames);
return redisKey;
}

**Comment by alexxiyang** [comment]
请升级至3.0.0，已经解决这个问题。
需要principal类实现`org.crazycake.shiro.AuthCachePrincipal`接口
