### ISSUE TITLE
principal 如果是String 类型，登陆用户的authorizationCache key重复，从2.4.2.1升级2.8.4发现的

### ISSUE THREAD

**Issue by zhangtr** [alexxiyang/shiro-redis#44]
principal 如果是String 类型，登陆用户的authorizationCache key重复，从2.4.2.1升级2.8.4发现的

**Comment by alexxiyang** [comment]
目前已经解决，请升级到3.0.0，principal现在必须实现 AuthCachePrincipal接口以提供key
