### ISSUE TITLE
shiro redis doReadSession too many times

### ISSUE THREAD

**Issue by FlowerWrong** [alexxiyang/shiro-redis#47]
我阅读了以下您的解决方案，有一个问题想请教一下，这里`doReadSession`的时候从`ThreadLocal`获取，不会出现redis里面的session已经被更新过或者已经删除，而`ThreadLocal`还是旧的情况吗？

[RedisSessionDAO.java#L124-L179](https://github.com/alexxiyang/shiro-redis/blob/master/src/main/java/org/crazycake/shiro/RedisSessionDAO.java#L124-L179)

相关[issue 19](https://github.com/alexxiyang/shiro-redis/issues/19)

**Comment by FlowerWrong** [comment]
实际测试也是如此，确实会拿到旧的session，我在update，delete session也做了处理。

**Comment by alexxiyang** [comment]
threadlocal中的session只存在1s，用于解决shiro操作过程中多次读取redis的问题

**Comment by alexxiyang** [comment]
测试：
1. 设置 `redisSessionDAO.sessionInMemoryTimeout = 300000` 意为30s
2. 执行如下代码
```java
		// Try to get session from redis
        Session session = currentUser.getSession();
        
        // Try to set value to redis-based session
        session.setAttribute("someKey", "aValue");
        String value = (String) session.getAttribute("someKey");
        if (value.equals("aValue")) {
            log.info("Retrieved the correct value! [" + value + "]");
        }

        Session session2 = currentUser.getSession();
        session2.setAttribute("someKey", "bValue");
        String newValue = (String) session2.getAttribute("someKey");
        if (!newValue.equals("bValue")) {
            throw new RuntimeException();
        }
```
试验结果：
someKey被设置为bValue后，立即调用session.getAttribute("someKey")拿到的是bValue。
因为放入sessionMap中的Sesssion对象跟currentUser.getSession()拿到的对象是同一个对象。
```java
		SessionInMemory sessionInMemory = new SessionInMemory();
		sessionInMemory.setCreateTime(new Date());
		sessionInMemory.setSession(s);
		sessionMap.put(sessionId, sessionInMemory);
```

请问要如何才能重现该问题？通过update(session)和delete(session)做什么处理可以解决这个问题？
