### ISSUE TITLE
3.0版本 RedisSessionDAO  sessionsInThread 问题

### ISSUE THREAD

**Issue by deeplyloving** [alexxiyang/shiro-redis#49]
ThreadLocal  sessionsInThread 无 remove 调用。如果一直是新线程将会耗费大量内存。如果是线程池的情况 将有可能获取上一次的上下文

如果是解决 单次调用 多次使用调用doReadSession的问题 建议还是与  request 关联上

**Comment by alexxiyang** [comment]
关于与requedt关联上的方案，可否创建pull request？

**Comment by deeplyloving** [comment]
重写DefaultWebSessionManager的 retrieveSession 方法 是我参考网上的一些解决方案
这样可以达到 一次请求 只调用一次 doReadSession
/**
	 * 解决doReadSession多次访问问题
	 * 
	 * @author liucf
	 *
	 */
	public static class CustomDefaultWebSessionManager extends DefaultWebSessionManager{
		@Override
		protected Session retrieveSession(SessionKey sessionKey) throws UnknownSessionException {
			Serializable sessionId = getSessionId(sessionKey);
			if(sessionId == null){
				 return super.retrieveSession(sessionKey);
			}
	        ServletRequest request = WebUtils.getRequest(sessionKey);
	        Object sessionObj = request.getAttribute(sessionId.toString());
            if (sessionObj != null) {
                return (Session) sessionObj;
            }
	        Session s = super.retrieveSession(sessionKey);
	        if (request != null && null != sessionId) {
	            request.setAttribute(sessionId.toString(), s);
	        }
			return s;
		}
	}

       @Bean
	public SessionManager createDefaultWebSessionManager(SessionDAO sessionDAO){
		DefaultWebSessionManager sessionManager = new CustomDefaultWebSessionManager();
        }

**Comment by alexxiyang** [comment]
Hi 非常感谢你的建议。很有启发性。

该方案实际实际上是重写了`DefaultSessionManager.retrieveSession()`方法。它的核心在于，增加以下逻辑：
如果request中有session则直接从request中获取session
```java
ServletRequest request = WebUtils.getRequest(sessionKey);
Object sessionObj = request.getAttribute(sessionId.toString());
if (sessionObj != null) {
    return (Session) sessionObj;
}
```

我有两点困惑：
1. 既然这样写比较好为什么Shiro官方不直接使用这种方案作为DefaultWebSessionManager的实现？
2. 这样做会不会造成Session于状态有关了。因为将Session存储在Redis可是实现无状态的服务接口，如果直接从request中获取，可能会造成request中的session影响了真实的session。 比如这种场景：

前提：
    1. 我们的系统是一个在线日志系统，类似印象笔记，或者有道云笔记
步骤：
    1. 用户打开了两个ui，比如一个是电脑上的浏览器，一个是手机app。这种场景很常见
    2. 用户在手机app上修改了session，需要浏览器中的session也同时修改
    3. 由于我们直接从request中获取sesison，而不是从redis中获取，所以用户的浏览器一直从request中拿到旧的Session

**Comment by deeplyloving** [comment]
我不知道为什么shiro 官方 没有将 session绑定到request中。
但我觉得 request中主 session 基本上也是无状态。。request 仅仅是一次请求。 次请求而已。理论上 会对 任何 会话 任何 请求 产生影响。

关于。用户打开两个终端 。。一个电脑浏览器  一个手机app      
一般情况下 这种 应该属于两个不同的会话。。完全两个不相关的session   不会因为我pc注销了该次会话而手机app也跟着退出了。。这不科学。
除非是第 “单点登陆”（这里指单终端登陆哈），一个地方登陆别的终端 全注销退出

关于拿旧session问题。。。 这个我觉得也是有些多于的考虑。 同一次请求 本身就应该是同一个session
我们现在要解决的问题就是 同一次request 多次 doReadSession的问题。

**Comment by alexxiyang** [comment]
为了防止以下两种情况的发生

1. 处于设计考虑，开发者将某些多平台共通的属性放在session中
2. 操作者的失误将某些需要共通的属性放在session中
不倾向使用重写`DefaultWebSessionManager`的方法。从框架角度考虑，需要考虑所有的情况

重写`DefaultWebSessionManager`的方法不属于`shiro-redis`的一部分，我们只能建议开发者这么做。开发者有权选择是否要这么做。我们必须照顾到不愿意这样做的用户，比如他原本已经重写了`DefaultWebSessionManager`，并不想将我们的逻辑加入`DefaultWebSessionManger`中。

**Comment by deeplyloving** [comment]
@alexxiyang    你说的没毛病。 多次doReadSession 本来就是 shiro 自身应该处理好的问题。
                       重写DefaultWebSessionManager 也是无耐之举。 确实也不应该属于 shiro-redis该处理的问题。
                      但 ThreadLocal sessionsInThread  应该还是需要优化。这里 隐患还是有些大

**Comment by WwJoyous** [comment]
sessionsInThread 都是在doReadSession 的时候在进行set、get。这中间是不是忽略了session dao的update操作，会不会导致不一致的问题尼？ 我现在遇到的问题是登陆之后偶尔会出现登陆失效的问题(就是登陆后在首页又跳转到登陆页面了)，我疑问是不是取到的信息不一致的问题？我把sessionsInThread 的去掉就可以了。我是向oracle中写入的，是不是要写入时间的问题尼？

**Comment by alexxiyang** [comment]
听起来的确是这个问题，我会将update操作也cover到周末发布的新版本中去

**Comment by alexxiyang** [comment]
3.2.2版本在  update 时也同时会更新 sessionInMemory。并且加入了 sessionInMemory 开关： 
1. Include sessionInMemory update in sessionDAO.doUpdate
2. Add sessionInMemoryEnabled to turn on/off sessionInMemory
