### ISSUE TITLE
关于 shiro-redis的2点建议或者疑问

### ISSUE THREAD

**Issue by deeplyloving** [alexxiyang/shiro-redis#50]
@alexxiyang 
由于没法回邮件。只好在这里交流一下。
我是从2.4.2.1-RELEASE开始 用贵框架的

关于 shiro-redis的2点建议或者疑问
1.关于AuthCachePrincipal   接口。定义一个接口固然比较好
但同时导致对原有代码有一定的侵入性。能不能考虑 如果实现了AuthCachePrincipal  则以AuthCachePrincipal 为准
如果没有实现AuthCachePrincipal   接口。则通过默认反射 getId()   getUniqeId() getCode(） 之类的固定方法来实现
获取凭证的唯一标识。或者 支持 setAuthCacheKeyMethod   这样不至于 需要修改原来的代码。只需要修改配置或者shiro相关配置代码即可
2.我不知道出于什么原因 最近发布的 版本中 把从 session中获取过期时间 改成 RedisSessionDAO.setExpire
   我觉得可以保留RedisSessionDAO.setExpire  如果 没有主动 setExpire   还是以  session中的gettimeout为准会好一些
   shiro-redis 作为 shiro 缓存以及session共享持久的补充。最好是 设置尽量以shiro中的设置为准。当然可以支持shiro-redis独立设置。在保持shiro固有的用法上 添加 shiro-redis独有的支持。

当下spring boot 盛行。是否可以考虑支持starter   这样cachemanager 或者 sessiondao都可以得到一定的简化

**Comment by alexxiyang** [comment]
1. 非常抱歉，由于Principal是一个Object，由于水平有限，所以我一直没找到类似getId(), UniqeId(),getCode(） 之类的固定方法。才使用了AuthCachePrincipal，实为下策。请问关于这个方法，可否有什么建议？
2. 现在把Session对象在Redis中的存活时间的设置权完全交给用户是因为有的用户说需要让Session在达到Timeout后，依然存活在Redis中，而不是直接销毁它。
     2.1  我担心用户由于自己的失误将expire设置的比Timeout更短，导致错误，所以我提供了一个警告，如果expire比timeout更短，则会提示"Redis session expire time: xxx is less than Session timeout: xxx. It may cause some problems." 
     2.2 之所以做成提示而不是强制的修改为Session.timeout是因为这可能会导致不熟悉源码的用户发现尝试修改expire无效，但是又不知道其实是因为我们做了一个他意想不到的小动作，这会让用户很沮丧。我想我们都经历过类似的事情，这是代码的一个坏味道
3. spring-boot我还没用过。这个建议很好，我会开始支持spring-boot

**Comment by alexxiyang** [comment]
关于#2 我会在下一个版本增加：
RedisSessionDAO.expire=-2 即使用shiro的session timeout，并将-2作为默认值。这样会不会好一些

**Comment by deeplyloving** [comment]
@alexxiyang 
关于第1点  我想是不是可以这样
      //principalKeyMethod可通过RedisCacheManager设置
	private String principalKeyMethod="getId";
	private Object getRedisKeyFromPrincipalCollection(PrincipalCollection key) {
		Object redisKey = null;
		Object primaryPrincipal = key.getPrimaryPrincipal();
		if (primaryPrincipal instanceof AuthCachePrincipal) {
			AuthCachePrincipal principal = (AuthCachePrincipal) primaryPrincipal;
			redisKey = principal.getAuthCacheKey();
        }else if(principalKeyMethod!=null && principalKeyMethod.trim().length()>0) {
        	try {
				Method m = primaryPrincipal.getClass().getDeclaredMethod(principalKeyMethod);
				redisKey = m.invoke(primaryPrincipal);
			} catch (NoSuchMethodException | SecurityException e) {
				e.printStackTrace();
			} catch (IllegalAccessException e) {
				e.printStackTrace();
			} catch (IllegalArgumentException e) {
				e.printStackTrace();
			} catch (InvocationTargetException e) {
				e.printStackTrace();
			}
        }
		if(redisKey == null)throw new PrincipalInstanceException("无法获取凭证唯一key");
		return redisKey;
	}

关于第2点。。我的认为还是 尽量设置上 以 shiro 原生设置为主。。shiro-redis 拓展为辅。 使用的时候 只要把shiro设置好。shiro-redis 只要配置几个实例即可就完全可以使用。   如果对缓存时间有特殊需求  则可以对shiro-redis单独设置。普通用户 只要配置好shiro 就好了。

**Comment by alexxiyang** [comment]
1. 用反射可以不需要修改代码，不错，下一个版本会加入用配置文件来设定id:
```ini
# use principalId to define the method which used to get authorization id,
# For example:
# If you use UserInfo as principal object and you set cacheManager.principalId=username
# shiro-redis will use userInfo.getUsername() to get the authorization id of UserInfo
# 
#
cacheManager.principalId=username
```
2. RedisSessionDAO.expire=-2 即使用shiro的session timeout，并将-2作为默认值
3. 下一个版本会使用setex代替 set 和 expire
4. 建议你使用md语法标记代码，可读性比较高

**Comment by alexxiyang** [comment]
3.1.0 发布：
1. 使用 principalIdFieldName 配置id字段，不需要使用AuthCachePrincipal
2. RedisSessionDAO.expire增加-2，表示使用session 的timeout作为expire，并且设定 -2为默认值
