### ISSUE TITLE
springboot中使用shiro贵框架后SecurityUtils.getSubject()都获取不到了

### ISSUE THREAD

**Issue by xiaojun515688** [alexxiyang/shiro-redis#51]
有遇到这种情况吗

**Comment by alexxiyang** [comment]
没有，不过我没有用过spring-boot。日志中有提示什么异常吗

**Comment by xiaojun515688** [comment]
那如果没有springboot集成的那个redis的话，那相当于是直接通过maven redis版本这样去做的是吗？ 用springboot的时候日志中也没看到有用的提示，SecurityUtils这个对象一直为空。

**Comment by alexxiyang** [comment]
是的，用maven来引入shiro-redis。

**Comment by xiaojun515688** [comment]
有demo可以借鉴吗

**Comment by alexxiyang** [comment]
https://github.com/alexxiyang/shiro-redis-spring-tutorial

**Comment by xiaojun515688** [comment]
方便加个联系方式吗？拜谢

**Comment by xiaojun515688** [comment]
我这里使用springboot后一直获取不到SecurityUtils.getSubject()这个，目前查不到原因

**Comment by xiaojun515688** [comment]
非常感谢你的例子和上面的回复，问题已经得到解决了，定位出是有的包冲突了，导致相互引用指向出了问题，现在问题已经好了

**Comment by alexxiyang** [comment]
很高兴能帮上你
