### ISSUE TITLE
RedisSessionDAO 设置过期时间不起作用，还是按照shiro本身默认半个小时就失效了

### ISSUE THREAD

**Issue by xiaojun515688** [alexxiyang/shiro-redis#53]
@Bean
    public RedisSessionDAO redisSessionDAO(){
        RedisSessionDAO redisSessionDAO = new RedisSessionDAO();
        redisSessionDAO.setRedisManager(redisManager());
        //存储一天
        redisSessionDAO.setExpire(60*60*24);
        return redisSessionDAO;
    }

-

**Comment by alexxiyang** [comment]
请确保使用的是 3.0.0 版本

**Comment by xiaojun515688** [comment]
确定是3.0.0的版本
<dependency>
			<groupId>org.crazycake</groupId>
			<artifactId>shiro-redis</artifactId>
			<version>3.0.0</version>
		</dependency>

**Comment by alexxiyang** [comment]
所谓的“失效”指的是session失效了，还是session对象在redis中被删除了？
redisSessionDAO.setExpire 设置的是session对象在redis中的存活时间，而不是session的有效时间。如果redisSessionDAO.setExpire比session的过期时间长，那么可以达到session过期后session在redis中的对象还存活。
所以就算redisSessionDAO.setExpire设置的很长，session的过期时间是不会变的

**Comment by alexxiyang** [comment]
非常抱歉，之前设定为让用户自己定义过期时间的方式其实不妥。
请升级至 3.1.0，在3.1.0中 redisSessionDAO.expire 的默认值为 -2，使用-2代表：redis中的session对象的expire事件自动设定为session的timeout时间。
