### ISSUE TITLE
关于使用shiro-redis的会话管理的问题

### ISSUE THREAD

**Issue by yunzhao824** [alexxiyang/shiro-redis#54]
现在需要通过session监听进行会话管理，但是配置的RedisManager的过期不能触发shiro的会话过期，设置shiro的过期也不能自动完成redis的缓存更新

**Comment by alexxiyang** [comment]
请升级至 3.1.0，在3.1.0中 redisSessionDAO.expire 的默认值为 -2，设置为-2则redis中的session对象的expire事件自动设定为session的timeout时间。
