### ISSUE TITLE
shiro-redis从2.4升级到3.0后报错

### ISSUE THREAD

**Issue by yunzhao824** [alexxiyang/shiro-redis#56]
错误信息如下
org.crazycake.shiro.exception.PrincipalInstanceException: Principal must implement org.crazycake.shiro.AuthCachePrincipal.
shiro-redis will get the key for store authorization object in Redis from org.crazycake.shiro.AuthCachePrincipal
So please use AuthCachePrincipal to tell shiro-redis how to get the cache key
 For example: There is a class UserInfo which implements org.crazycake.shiro.AuthCachePrincipal. You can use this class to initial SimpleAuthenticationInfo like this:
 UserInfo userInfo = new userInfo();
 new SimpleAuthenticationInfo(userInfo, "123456", "realm1")
	at org.crazycake.shiro.RedisCache.getRedisKeyFromPrincipalCollection(RedisCache.java:134) ~[shiro-redis-3.0.0.jar:na]
	at org.crazycake.shiro.RedisCache.getStringRedisKey(RedisCache.java:123) ~[shiro-redis-3.0.0.jar:na]
	at org.crazycake.shiro.RedisCache.getRedisCacheKey(RedisCache.java:112) ~[shiro-redis-3.0.0.jar:na]
	at org.crazycake.shiro.RedisCache.get(RedisCache.java:61) ~[shiro-redis-3.0.0.jar:na]
	at org.apache.shiro.realm.AuthorizingRealm.getAuthorizationInfo(AuthorizingRealm.java:328) ~[shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.realm.AuthorizingRealm.isPermitted(AuthorizingRealm.java:462) ~[shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.realm.AuthorizingRealm.isPermitted(AuthorizingRealm.java:458) ~[shiro-core-1.3.2.jar:1.3.2]
	at org.apache.shiro.authz.ModularRealmAuthorizer.isPermitted(ModularRealmAuthorizer.java:223) ~[shiro-core-1.3.2.jar:1.3.2]

**Comment by alexxiyang** [comment]
正如错误信息提示的 principal需要实现AuthCachePrincipal

3.0.0新增接口

**Comment by yunzhao824** [comment]
能具体点吗，我需要在哪个类上实现这个接口？

在 2018-05-30 10:01:31，"alex" <notifications@github.com> 写道：
正如错误信息提示的 principal需要实现AuthCachePrincipal

3.0.0新增接口

**Comment by alexxiyang** [comment]
参考before use 段落

**Comment by alexxiyang** [comment]
https://github.com/alexxiyang/shiro-redis/blob/master/README.md

**Comment by yunzhao824** [comment]
按照你的文档改了，仍然报同样的错。
代码如下：
//登录验证
    protected AuthenticationInfo doGetAuthenticationInfo(AuthenticationToken authenticationToken) throws AuthenticationException {
        String userCode = (String) authenticationToken.getPrincipal();
        String password = new String((char[]) authenticationToken.getCredentials());
        
        // 查询用户信息
        SysUserDTO sysUser = sysApiService.getLoginUserByUserCode(userCode);

        if (null == sysUser) {
            throw new UnknownAccountException();
        }
        if (!sysUser.getPassword().equals(MD5Util.MD5(password + sysUser.getSalt()))) {
            throw new IncorrectCredentialsException();
        }
        if (sysUser.getUseable() == 0) {
            throw new LockedAccountException();
        }

        UserInfo userInfo = new UserInfo();
        BeanUtils.copyProperties(sysUser, userInfo);
        
        AuthenticationInfo authcInfo = new SimpleAuthenticationInfo(userInfo, password, getName());

------------------------------------------------------------------
UserInfo.java
public class UserInfo implements Serializable, AuthCachePrincipal {
    private static final long serialVersionUID = -6477843453976551075L;

    private String id;

    private String userCode;

    private String userName;

    ...

    @Override
    public String getAuthCacheKey() {
        return this.getUserCode();
    }

}

**Comment by alexxiyang** [comment]
可否断点调试 RedisCache 类 line 133:
```java
if (!(principalCollection.getPrimaryPrincipal() instanceof AuthCachePrincipal)) {
            throw new PrincipalInstanceException();
        }
```
观察此处 principalCollection.getPrimaryPrincipal() 取出的对象是否是UserInfo对象？

**Comment by alexxiyang** [comment]
Any updates?

**Comment by alexxiyang** [comment]
请升级至3.1.0，3.1.0取消了AuthCachePrincipal接口，转而使用反射来获取auth的redis对象id，请在 `cacheManager.principalIdFieldName` 中配置id字段，具体请参考README.md
