### ISSUE TITLE
org.crazycake.shiro.RedisCache.keys() 返回键值不匹配的问题

### ISSUE THREAD

**Issue by Amazingwujun** [alexxiyang/shiro-redis#57]
如果使用 其他对象（比如 java.util.Date）做 K ，那么keys() 返回的K结果集只是字符串而已，并非是我想要的K

**Comment by alexxiyang** [comment]
如果用别的对象做Key就需要自定义 serializer咯：
https://github.com/alexxiyang/shiro-redis#serializer
不过，挺好奇什么场景需要用Date做K，可以把Date转化成字符串格式的时间戳么？这样可能会实现起来比较简单，不需要自定义serializer

**Comment by Amazingwujun** [comment]
> 
    private byte[] keySerialize(K key) {
        byte[] keyBytes = valueSerializer.serialize(key);
        int keyLength = keyBytes.length;

        byte[] newKey = new byte[prefix_len + keyLength];

        //开始装配 newKey
        System.arraycopy(prefix, 0, newKey, 0, prefix_len);
        System.arraycopy(keyBytes, 0, newKey, prefix_len, keyLength);

        return newKey;
    }

    @SuppressWarnings("unchecked")
    private K keyDeserialize(byte[] keyBytes) {
        int length = keyBytes.length;

        byte[] key = new byte[length - prefix_len];

        //开始装配 newKey
        System.arraycopy(keyBytes, prefix_len, key, 0, length - prefix_len);

        return (K) valueSerializer.deserialize(key);
    }

我把 key 的序列化分成两部分了，反序列化也是如此，这样就不存在特殊情况了

**Comment by Amazingwujun** [comment]
其实问题在于我不怎么熟悉 shiro ，不清楚 它会使用什么类型的 key，所以智能使用这中办法了

**Comment by Amazingwujun** [comment]
如果使用了这种序列化，那么 AuthCachePrinciple 这个接口可以不用了

**Comment by alexxiyang** [comment]
3.1.0 发布：
1. 使用 principalIdFieldName 配置id字段，不需要使用AuthCachePrincipal
2. RedisSessionDAO.expire增加-2，表示使用session 的timeout作为expire，并且设定 -2为默认值
3. 使用scan实现dbsize
