### ISSUE TITLE
org.crazycake.shiro.RedisCache.size() 返回数量可能不符合期望的问题

### ISSUE THREAD

**Issue by Amazingwujun** [alexxiyang/shiro-redis#58]
public int size() {
		Long longSize = new Long(redisManager.dbSize());
		return longSize.intValue();
	}
你直接用的 redis commonds dbsize,如果别的程序也有在使用这个 redis 库，那么 size() 的返回明显不对，比如我使用的就是 redis 集群，以下为个人修改。

  ```
public int size() {
        String pattern = "*";

        RedisFuture<List<byte[]>> future = conn.keys(keySerialize(pattern));

        try {
            List<byte[]> list = future.get();

            return list.size();
        } catch (InterruptedException | ExecutionException e) {
            throw new CacheException(e.getMessage(), e);
        }
    }
```

**Comment by Amazingwujun** [comment]
我的办法也有问题，当 Key 非常多的时候，那么会出现性能瓶颈。可以把 redis commands keys 改为 scan

**Comment by alexxiyang** [comment]
你说得对，非常感谢你的意见，下一个版本会使用scan来实现dbsize！

**Comment by alexxiyang** [comment]
3.1.0 发布：
1. 使用 principalIdFieldName 配置id字段，不需要使用AuthCachePrincipal
2. RedisSessionDAO.expire增加-2，表示使用session 的timeout作为expire，并且设定 -2为默认值
3. 使用scan实现dbsize
