### ISSUE TITLE
实现权限和认证缓存的原理是什么，如果要实现登录退出时清除缓存该如何实现？

### ISSUE THREAD

**Issue by WillOfCloud** [alexxiyang/shiro-redis#59]
作者你好，因为本人对redis不是很熟，直接采用该框架确实方便了很多。如标题所述，我想实现**退出时清除登录时的认证和授权**，请问该如何实现，希望能点拨一下，我再去研究，谢谢！

**Comment by Amazingwujun** [comment]
你在调用 Subject.logout()时，shiro 会帮你清楚登录时的认证与授权，不需要手动处理 redis 中的数据

**Comment by Amazingwujun** [comment]
另外这个框架目前看来BUG不少，要结合项目的情况来使用，切勿直接使用在要上线的项目。

**Comment by WillOfCloud** [comment]
好的，谢谢提醒

**Comment by WillOfCloud** [comment]
@Amazingwujun 
你好，再请教一下：Subject.logout()是个无参方法，似乎并不能确认当前用户是谁，所以clear时又是怎么确定的呢？

**Comment by Amazingwujun** [comment]
可以确定的，当你发送请求时，就已经携带了身份信息了（默认是通过 cookie 中的 sessionId）

**Comment by WillOfCloud** [comment]
@Amazingwujun 
谢谢，请问是否试过和springboot集成，我今天发现自定义的HashedCredentialsMatcher失效，以@bean形式是注入了的，但是并没有发挥作用，密码依然是明文才正确。

**Comment by Amazingwujun** [comment]
shiro 官方有做这方面的工作，你可以引入这个依赖
```
       <dependency>
            <groupId>org.apache.shiro</groupId>
            <artifactId>shiro-spring-boot-web-starter</artifactId>
            <version>1.4.0-RC2</version>
        </dependency>
```
同时去查看 demo。
