### ISSUE TITLE
出现一个序列化的问题，请指教

### ISSUE THREAD

**Issue by leehuajun** [alexxiyang/shiro-redis#60]
There was an unexpected error (type=Internal Server Error, status=500).
org.apache.shiro.session.UnknownSessionException: org.crazycake.shiro.exception.SerializationException: serialize error, object=org.apache.shiro.session.mgt.SimpleSession,id=684dc670-6ac4-47ab-bf11-52960c8cc6c3

谢谢！

**Comment by alexxiyang** [comment]
可否附上完整的错误堆栈（包含错误行数和类名）？

**Comment by yythlj** [comment]
这个问题解决了吗？使用了最新的springBoot-starter的相关工程，包括其中配置是在shiro-redis.application而非springBoot默认配置文件，自定义的SessionManage等问题都已自行解决，session已经能存进redis，但是还是存在这个问题，一旦使用SecurityUtils.getSubject().getSession().setAttribute报错，错误和18年上面这位兄弟一样，断点到时RedissSessionDao的saveSession方法，53和54行，调试发现SimpleSession的attributes成员是null

**Comment by yythlj** [comment]
而且日志调至debug也是只有这一句error提示信息
