### ISSUE TITLE
关于 SimpleSession 几个关键transient字段的序列化问题

### ISSUE THREAD

**Issue by DevilMayCrySamsara** [alexxiyang/shiro-redis#61]
你好，我想问一下,对于shiro SimpleSession类，有下面
    private transient Serializable id;
    private transient Date startTimestamp;
    private transient Date stopTimestamp;
    private transient Date lastAccessTime;
    private transient long timeout;
    private transient boolean expired;
    private transient String host;
    private transient Map<Object, Object> attributes;
字段都是 transient 的，作者也给了讨论经历：
 // ==============================================================
    // NOTICE:
    //
    // The following fields are marked as transient to avoid double-serialization.
    // They are in fact serialized (even though 'transient' usually indicates otherwise),
    // but they are serialized explicitly via the writeObject and readObject implementations
    // in this class.
    //
    // If we didn't declare them as transient, the out.defaultWriteObject(); call in writeObject would
    // serialize all non-transient fields as well, effectively doubly serializing the fields (also
    // doubling the serialization size).
    //
    // This finding, with discussion, was covered here:
    //
    // http://mail-archives.apache.org/mod_mbox/shiro-user/201109.mbox/%3C4E81BCBD.8060909@metaphysis.net%3E
    //
    // ==============================================================
加上这个，是为了避免二次序列化，如果用redis来存储的话，应该会无视transient特性，这样会不会违背作者的意图？
版本是shiro-core-1.4.0

**Comment by alexxiyang** [comment]
这个问题的影响范围目前不明。请问是否有在实际环境下遇到由此引起的问题？
