### ISSUE TITLE
与CAS结合使用貌似不行

### ISSUE THREAD

**Issue by wendrewshay** [alexxiyang/shiro-redis#62]
不知道有没有考虑认证后返回SimpleAuthenticationInfo时与CAS结合使用的问题，我没有找到好的方法，不知道作者有何解决方案？

**Comment by alexxiyang** [comment]
请问你说的CAS是 https://shiro.apache.org/cas.html 吗？

**Comment by wendrewshay** [comment]
> 请问你说的CAS是 https://shiro.apache.org/cas.html 吗？

是的

**Comment by alexxiyang** [comment]
没用过 CAS，请问有报什么异常吗

WenQiang.Xia <notifications@github.com> 于2018年12月7日周五 上午2:12写道：
