### ISSUE TITLE
principalIdFieldName 属性应用问题

### ISSUE THREAD

**Issue by malagebi** [alexxiyang/shiro-redis#64]
在整合期间，只要操作涉及到 权限都会报以下错误：
        class java.lang.String must has getter for field: authCacheKey or id We need a field to identify this Cache Object in Redis. So you need to defined an id field which you can get unique id to identify this principal. For example, if you use UserInfo as Principal class, the id field maybe userId, userName, email, etc. For example, getUserId(), getUserName(), getEmail(), etc. Default value is authCacheKey or id, that means your principal object has a method called "getAuthCacheKey()" or "getId()"
能否解答一下 这个属性 设置时需要注意什么，该属性有什么用处。

**Comment by malagebi** [comment]
找到问题所在了，  关键位置其实是  doGetAuthenticationInfo 方法 返回 SimpleAuthenticationInfo 对象时，第一个参数应该是  用户表的实体类。之前没注意

**Comment by alexxiyang** [comment]
这个属性用来为权限对象设置redia id使用，一般用用户ID或者email等唯一id。但不限于此，只要是唯一就行
