### ISSUE TITLE
可以支持lettuce嘛

### ISSUE THREAD

**Issue by Baymax6** [alexxiyang/shiro-redis#67]
后台spring boot用的是2.0.3版本，默认用的lettuce而不是Jedis,今天发现登录异常查了一下发现默认用的是Jedis

**Comment by alexxiyang** [comment]
咦？spring boot的哪个starter使用的是 lettuce?

Alex Mason <notifications@github.com> 于2018年8月16日周四 下午6:07写道：

**Comment by Baymax6** [comment]
Spring Boot 2.0及其以上版本默认由jedis改为了lettuce

**Comment by samson886** [comment]
@Baymax6 你不是扯犊子吗？
![image](https://user-images.githubusercontent.com/8944097/45581862-9c540980-b8d8-11e8-8c56-358fc6acd3bb.png)

**Comment by cdmamata** [comment]
你好，我也遇到lettuce 问题，spring boot 版本 2.0.6，默认使用的 lettuce，但是shiro-redis 使用的是 jedis ，因此不得不引入 jedis ，可否支持lettuce

**Comment by alexxiyang** [comment]
可以哦！

**Comment by alexxiyang** [comment]
@cdmamata 虽然下一个版本会加入对lettuce的支持，但是由于shiro-redis会同时支持jedis和lettuce，所以Maven的dependence 依然会自动加入对jedis的依赖，这样可以吗？

**Comment by cdmamata** [comment]
> @cdmamata 虽然下一个版本会加入对lettuce的支持，但是由于shiro-redis会同时支持jedis和lettuce，所以Maven的dependence 依然会自动加入对jedis的依赖，这样可以吗？

我觉得没问题，毕竟还需要考虑其他人可能用 jedis ， 只要能够使 lettuce 跟 jedis 可配置化，按需使用即可

**Comment by Hipple** [comment]
> @cdmamata 虽然下一个版本会加入对lettuce的支持，但是由于shiro-redis会同时支持jedis和lettuce，所以Maven的dependence 依然会自动加入对jedis的依赖，这样可以吗？

请问下一版本大约会在什么时候发布？

**Comment by alexxiyang** [comment]
@Baymax6 @cdmamata @Hipple 可否告知如果使用spring-boot 2.0.3 会有什么异常？
第三方包使用的包并不会让开发者直接使用，所以并不会有什么影响。比如有两个第三方包，一个使用FastJson另一个使用Jackson，其实都是可以共存的。因为开发者并不是直接使用Jackson或者FastJson。

如果可以的话，暂时不加入lettuce的支持，因为并没有看到太大的必要。

**Comment by Hipple** [comment]
> @Baymax6 @cdmamata @Hipple 可否告知如果使用spring-boot 2.0.3 会有什么异常？
> 第三方包使用的包并不会让开发者直接使用，所以并不会有什么影响。比如有两个第三方包，一个使用FastJson另一个使用Jackson，其实都是可以共存的。因为开发者并不是直接使用Jackson或者FastJson。
> 
> 如果可以的话，暂时不加入lettuce的支持，因为并没有看到太大的必要。

不会有什么异常，只是需要分别针对jedis，lettuce进行配置，使用或升级过程稍显繁琐。
如果没有支持计划的话，是否接受PR？

**Comment by alexxiyang** [comment]
可以接受PR

**Comment by wencynyu** [comment]
我把源码下载下来以后修改了Redis连接类就能用了。
`
在WorkAloneRedisManager类中：
protected abstract RedisConnection getRedis();

RedisSentinelManager类和RedisManager类（继承了WorkAloneRedisManager的类）中，将原有的jedis连接获取删除后补充自己的连接方式：
@Autowired
    private RedisConnectionFactory redisConnectionFactory;

    @Override
    protected RedisConnection getRedis() {
        return redisConnectionFactory.getConnection();
    }

另外会一些琐碎的错误提示，自行搜索即可解决。
`
