### ISSUE TITLE
1、继承 DefaultWebSessionManager 后 setGlobalSessionTimeout 无效 2、springboot整合shiro-redis后jedis 操作十次就阻塞了

### ISSUE THREAD

**Issue by JackMeiiii** [alexxiyang/shiro-redis#68]
1、自己写了一个SessionManager继承DefaultWebSessionManager ，然后注入bean的时候setGlobalSessionTimeout 无效，还是默认的半小时。shiro是1.4.0  shiro-redis 是 3.1.0

2、shiro-redis 从2.4.1.release更新到 3.1.0之后jedis操作十次数据库 再请求就阻塞在那里，没有响应也没有返回值

**Comment by JackMeiiii** [comment]
不好意思，补充一下shiro-redis 用的是3.1.0  shiro 是1.4.0

**Comment by alexxiyang** [comment]
3.1.0 跟 shiro-spring-boot-starter 不兼容。是否尝试使用3.2.1再试试？
