### ISSUE TITLE
3.1版本的cacheManager.principalIdFieldName问题

### ISSUE THREAD

**Issue by lhy117** [alexxiyang/shiro-redis#72]
如果user对象的id字段在父类中  还是会抛异常

还有一个问题  为什么强制new SimpleAuthenticationInfo(userInfo, "123456", getName());这样构建
userinfo替换成字符串不支持吗？

**Comment by littleBurro** [comment]
遇到了同样的问题-----------
如果user对象的id字段在父类中 还是会抛异常

**Comment by alexxiyang** [comment]
该问题在 3.2.1 版本中修复了，请升级至 3.2.1
