### ISSUE TITLE
升级到3.1.0之后 如何 兼容 redis 集群 和单点两种模式？

### ISSUE THREAD

**Issue by M-sunary** [alexxiyang/shiro-redis#74]
> 背景：
   公司产品 QA环境 redis 是单点模式( RedisManager )的，生产环境是 集群模式( RedisClusterManager )。
升级 shiro-redis 之前用的2.1.4.RELEASE 也就是单点模式的redis （RedisManager）;
升级之后 shiro-redis 用的 3.1.0的 集群模式的redis (RedisClusterManager )

升级之后 QA环境报错：ERR This Instance has cluster support disabled;
升级之前 生产环境报错： JedisMovedDataException

所以想问下 怎么兼容这两种情况都能运行。
麻烦了~！

**Comment by alexxiyang** [comment]
这个没法搞，而且不建议这么做。建议qa环境也搭建一个小型集群，否则如果有什么问题是在集群上才会出现的，你在qa环境就无法发现这个问题了
