### ISSUE TITLE
shiro1.40 和 现在的版本3.1.0冲突吗

### ISSUE THREAD

**Issue by wanniwa** [alexxiyang/shiro-redis#75]
用idea的时候有一个pom依赖分析，分析出，shiro-redis依赖的是1.2.6的shiro 和 我自己依赖引入的1.4.0冲突，还是说idea这个分析我不用管它

**Comment by alexxiyang** [comment]
请稍等几天，我会发布新版本的shiro-redis。新版本的shiro-redis会使用1.3.2的shiro. 1.4太新了，暂时不会支持

**Comment by alexxiyang** [comment]
以将shiro-redis升级为使用1.3.2.请升级shiro-redis至3.2.1
