### ISSUE TITLE
mavenMissing artifact com.sun:tools:jar:1.8.0

### ISSUE THREAD

**Issue by klguang** [alexxiyang/shiro-redis#76]
![default](https://user-images.githubusercontent.com/25003367/48300087-0fad7c80-e512-11e8-8c9c-b331f7e52b56.png)

**Comment by alexxiyang** [comment]
具体是什么异常呢？

**Comment by yxb3130** [comment]
用到sun的依賴包吧

**Comment by alexxiyang** [comment]
checkstyle 的依赖没有必要，下一个版本会去掉
