### ISSUE TITLE
Failed to deserialize 反序列化失败

### ISSUE THREAD

**Issue by skycyang** [alexxiyang/shiro-redis#78]
ByteArrayInputStream byteStream = new ByteArrayInputStream(bytes);
这里反序列化出错了，原因是我们的应用有多个版本在运行，每个版本的对象是有差异的，当一个版本的用户转到另一个版本后，他的登录信息就会在反序列化时失败。

**Comment by gjhuai** [comment]
@skycyang  我也遇到这样的问题，请问你怎么解决的？

**Comment by alexxiyang** [comment]
这里的多个版本指的是什么东西的多个版本？

**Comment by gjhuai** [comment]
就是同一个类在多个jar中存在

**Comment by alexxiyang** [comment]
这样的问题超过了shiro-redis的可控范围了

**Comment by skycyang** [comment]
我这边是不同版本使用了redis的不同库来规避这个问题
