### ISSUE TITLE
关于查询别的表时当前用户多次查询的问题

### ISSUE THREAD

**Issue by lcllge** [alexxiyang/shiro-redis#81]
我这边使用的是**springboot-1.5.7** 配合大佬的**_shiro-redis 3.2.1_** 出现以下问题,查询别的数据时会连带查询用户表当前用户,症状是: 查询别的表之后会去用当前用户id查询当前用户(在数据库中查询,目标表查询到几条就会查询当前用户几次),目前还没有解决,因为不是使用的starter,目前遇到这个问题

**Comment by alexxiyang** [comment]
请问有日志或者截图吗
