### ISSUE TITLE
logout后，在reids中身份认证的缓存还存在，没被清除

### ISSUE THREAD

**Issue by InCong** [alexxiyang/shiro-redis#83]
一开始我在返回的SimpleAuthenticationInfo中传入参数principal的是user对象，并且在RedisCacheManager中setPrincipalIdFieldName("username")
然后在logout之后，在追踪清除身份认证逻辑中发现，RedisCache中getStringRedisKey返回的是user.tostring后的对象，而不是一开始返回我定义的username
请问这个是什么原因？该如何修改（我并不想在SimpleAuthenticationInfo中传入username）

**Comment by alexxiyang** [comment]
您好，我使用 https://github.com/alexxiyang/shiro-redis-spring-boot-tutorial 无法重现改问题。请问可否提供：

1. shiro-redis 版本
2. shiro-redis 使用方式： ini？spring？spring-boot？
3. “追踪清除身份认证逻辑” 的代码，最好有debug截图

**Comment by dark-code** [comment]
您好，我也遇到了此问题，用的是3.3.1的starter
