### ISSUE TITLE
sessionMap的session清除问题？

### ISSUE THREAD

**Issue by jee2017** [alexxiyang/shiro-redis#88]
假如项目使用了线程池，而用户在最后一次操作时，getSessionFromThreadLocal中没有调用sessionMap.remove(sessionId)方法，那么这个session将一直保存在sessionMap中，直至服务器重启吗？那么是不是需要定期调用ThreadLocal的remove方法？

**Comment by jee2017** [comment]
既然是为了避免一次请求多次访问redis的问题而使用ThreadLocal，那么在setSessionToThreadLocal中把新的sessionInMemory存入sessionMap之前，为什么不把sessionMap清空？里面的缓存应该没有用了吧？

**Comment by alexxiyang** [comment]
不需要在新的sessionInMemory存入sessionMap之前，把sessionMap清空，因为doCreate的时候会校验sessionInMap的存活时间，所以你无法取到过期的SessionInMap中的session

**Comment by jee2017** [comment]
确实是无法取到过期的SessionInMap中的session，但是如果服务端运行一段时间后，sessionMap中的session不会越积越多吗？占用的内存也会越来越多吧？

**Comment by alexxiyang** [comment]
有道理，已经提交了commit，在新session被放入SessionInMap之前会先清除过期session

**Comment by alexchanchan** [comment]
我的项目经过压力测试后发现经常报内存溢出，dump内存查看发现是session在threadlocal没及时清除的原因，尤其是线程池设置越大越明显。我提个小小建议，如果用GuavaCache代替threadlocal，会不会好一点呢？

**Comment by alexxiyang** [comment]
3.2.2已经增加了清除threadlocal 中 session 的方法，请再次进行压力测试
