### ISSUE TITLE
使用springbot+redis+redis-session+shiro项目，能不能在创建RedisManager时直接使用boot的redis相关配置呢？

### ISSUE THREAD

**Issue by zhangyuxiansen2017** [alexxiyang/shiro-redis#91]
@Bean
    public RedisManager redisManager() {
        RedisManager redisManager = new RedisManager();
        redisManager.setHost("localhost");
        redisManager.setPort(6379);
        redisManager.setTimeout(0);
        redisManager.setPassword("123456");
        return redisManager;
    }
//这是我现在创建RedisManager的代码，能不能直接在此使用boot的redis的配置，而非自己填写host，端口等

**Comment by alexchanchan** [comment]
> ```
> @Bean
> public RedisManager redisManager() {
>     RedisManager redisManager = new RedisManager();
>     redisManager.setHost("localhost");
>     redisManager.setPort(6379);
>     redisManager.setTimeout(0);
>     redisManager.setPassword("123456");
>     return redisManager;
> }
> ```
> //这是我现在创建RedisManager的代码，能不能直接在此使用boot的redis的配置，而非自己填写host，端口等

`@Bean
    protected RedisManager redisManager(RedisProperties redisProperties) {
        RedisManager redisManager = new RedisManager();
        redisManager.setHost(redisProperties.getHost() + ":" + redisProperties.getPort());
        redisManager.setPassword(redisProperties.getPassword());
        JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
        if (redisProperties.getPool() != null) {
            jedisPoolConfig.setMaxIdle(redisProperties.getPool().getMaxIdle());
            jedisPoolConfig.setMinIdle(redisProperties.getPool().getMinIdle());
            jedisPoolConfig.setMaxTotal(redisProperties.getPool().getMaxActive());
            jedisPoolConfig.setMaxWaitMillis(redisProperties.getPool().getMaxWait());
        }
        redisManager.setJedisPoolConfig(jedisPoolConfig);
        return redisManager;
    }`

请参考

**Comment by alexxiyang** [comment]
shiro-redis已经实现了spring-boot-starter。使用方式见： https://github.com/alexxiyang/shiro-redis-spring-boot-tutorial
