### ISSUE TITLE
踢出用户的功能无法使用，踢出后，session还是存在，请问如何解决？谢谢！

### ISSUE THREAD

**Issue by billzw** [alexxiyang/shiro-redis#93]
踢出用户的功能无法使用，踢出后，session还是存在，请问如何解决？谢谢！
原来
Session session = sessionDAO.readSession(tempId);
session.setTimeout(0);	
即可踢出，采用shiro-redis后，就不行了。

**Comment by alexxiyang** [comment]
请问有日志或者截图吗？

**Comment by billzw** [comment]
没有日志，没有任何反应。

**Comment by alexxiyang** [comment]
设置了 session.setTimeout(0)  之后查看redis，该用户的session  还存在吗？

**Comment by billzw** [comment]
还在！所以提这个问题。

**Comment by billzw** [comment]
问题找到了
setTimeout(0)后，需要update，否则会无效。
谢谢！
