### ISSUE TITLE
3.2.3我是不是发现了一个bug.

### ISSUE THREAD

**Issue by wuyuanwei** [alexxiyang/shiro-redis#94]
大佬我错了，是我的错。请大佬说下，下面的问题

**Comment by wuyuanwei** [comment]
Map<Serializable, SessionInMemory> sessionMap = (Map<Serializable, SessionInMemory>) sessionsInThread.get();
		SessionInMemory sessionInMemory = sessionMap.get(sessionId);
		if (sessionInMemory == null) {
			return null;
		}
		long liveTime = getSessionInMemoryLiveTime(sessionInMemory);
		if (liveTime > sessionInMemoryTimeout) {
			sessionMap.remove(sessionId);
			return null;
		}

**Comment by wuyuanwei** [comment]
还有， pom.xml，引入
<dependency>
		    <groupId>org.crazycake</groupId>
		    <artifactId>shiro-redis</artifactId>
		    <version>3.2.2</version>
		</dependency>
时候报错。3.2.3不报。

**Comment by wuyuanwei** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
是则会一段报错

**Comment by wuyuanwei** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">`
这一段报错

**Comment by wuyuanwei** [comment]
用户登录之后，建立session. 这个session的ID和内容，我可不可以自定义呀？怎么实现？

**Comment by alexxiyang** [comment]
session的id可以自定义，但是这不是shiro-redis的范围。这是shiro本身的特性，参阅
https://shiro.apache.org/session-management.html#SessionManagement-CustomSessionIDs
内容不能自定义
