### ISSUE TITLE
ERROR org.crazycake.shiro.RedisSessionDAO - read session error. settionId=adb79750-ea4a-4326-81b7-5a696a8c861a

### ISSUE THREAD

**Issue by liulei008** [alexxiyang/shiro-redis#95]
ERROR org.crazycake.shiro.RedisSessionDAO - read session error. settionId=adb79750-ea4a-4326-81b7-5a696a8c861a，求作者帮忙解决下~~

**Comment by alexxiyang** [comment]
请问有更具体的异常信息吗？

**Comment by liulei008** [comment]
12:15:30.346 logback [] [] [http-nio-8000-exec-3] ERROR org.crazycake.shiro.RedisSessionDAO - read session error. settionId=682b7e52-c319-464c-8252-ec95730fd158
12:15:30.351 logback [] [] [http-nio-8000-exec-3] ERROR c.n.e.a.a.c.GlobalExceptionHandler - There is no session with id [682b7e52-c319-464c-8252-ec95730fd158]
org.apache.shiro.session.UnknownSessionException: There is no session with id [682b7e52-c319-464c-8252-ec95730fd158]
	at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:170)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSession(DefaultSessionManager.java:222)
	at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:118)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:249)
	at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141)

**Comment by liulei008** [comment]
![image](https://user-images.githubusercontent.com/18674070/54919040-b97a2c80-4f3a-11e9-8450-0589c17c1158.png)
提示反序列化的时候有问题

**Comment by Shi7Happens** [comment]
redisCacheManager.setPrincipalIdFieldName

对象要实现Serializable接口

**Comment by xuanj** [comment]
spring boot 在分离依赖jar，配置文件时，生产也会报这个错

**Comment by Rusell-Wu** [comment]
同样的问题，spring boot打包成jar并且分离依赖资源，会报ERROR org.crazycake.shiro.RedisSessionDAO - read session error. settionId=[]，There is no session with id []，在tomcat环境下和idea直接运行的环境下时正常的

**Comment by Rusell-Wu** [comment]
> spring boot 在分离依赖jar，配置文件时，生产也会报这个错

我解决了，分离打包的时候，这个错误是由于分离打包-序列化时使用的 ClassLoader不同导致找不到class，出现的现象就是在IDEA能正常运行，打包之后就会报there is not session的错误，解决的方法是在maven打包插件那里加<classifier>exec</classifier>，如下图所示
![image](https://user-images.githubusercontent.com/30775023/62338349-d20eda80-b50a-11e9-8f1d-c3173f59e338.png)

或者参考https://www.jianshu.com/p/32d38a7fd20a，这个我没试

**Comment by gorouter** [comment]
这个问题我在序列化时也遇到了，3.2.3版本，请问怎样解决？或者哪个版本没有这个问题？
public byte[] serialize(Object object) throws SerializationException {
        byte[] result = new byte[0];
        if (object == null) {
            return result;
        } else {
            ByteArrayOutputStream byteStream = new ByteArrayOutputStream(128);
            if (!(object instanceof Serializable)) {
                throw new SerializationException("requires a Serializable payload but received an object of type [" + object.getClass().getName() + "]");
            } else {
                try {
                    ObjectOutputStream objectOutputStream = new ObjectOutputStream(byteStream);
                    **objectOutputStream.writeObject(object);** // 这里报错了
                    objectOutputStream.flush();
                    result = byteStream.toByteArray();
                    return result;
                } catch (IOException var5) {
                    throw new SerializationException("serialize error, object=" + object, var5);
                }
            }
        }
    }

**Comment by Rusell-Wu** [comment]
> 这个问题我在序列化时也遇到了，3.2.3版本，请问怎样解决？或者哪个版本没有这个问题？
> public byte[] serialize(Object object) throws SerializationException {
> byte[] result = new byte[0];
> if (object == null) {
> return result;
> } else {
> ByteArrayOutputStream byteStream = new ByteArrayOutputStream(128);
> if (!(object instanceof Serializable)) {
> throw new SerializationException("requires a Serializable payload but received an object of type [" + object.getClass().getName() + "]");
> } else {
> try {
> ObjectOutputStream objectOutputStream = new ObjectOutputStream(byteStream);
> **objectOutputStream.writeObject(object);** // 这里报错了
> objectOutputStream.flush();
> result = byteStream.toByteArray();
> return result;
> } catch (IOException var5) {
> throw new SerializationException("serialize error, object=" + object, var5);
> }
> }
> }
> }
我是自己重写了一个序列化类和反序列化类解决的
