### ISSUE TITLE
关于什么时候过期？

### ISSUE THREAD

**Issue by xungegeblue** [alexxiyang/shiro-redis#96]
RedisSessionDAO redisSessionDAO = new RedisSessionDAO();
 redisSessionDAO.setKeyPrefix(CACHE_KEY);
 redisSessionDAO.setRedisManager(redisManager);
 redisSessionDAO.setExpire(10);
上面是我的代码，我设置了秒钟过期，然后页面不断刷新，shiro可以正常访问，10秒钟之后还是没有过期。
如果页面没有刷新，10秒之后就过期了。
请问下，过期的机制是否是用户不活动10秒才过期。
那么如果我想强制10秒后过期需要怎么操作呢？

**Comment by alexxiyang** [comment]
几乎所有的网站不断刷新页面session都不会过期。session就是这么设计的。如果你想强制10秒后过期。首先你要把你用来比较的基准时间写到session中，比如登陆时间。然后写一个拦截器。在每次请求的时候比较当前时间和登陆时间，如果大于10秒，则让其强制退出

**Comment by xungegeblue** [comment]
谢谢你的耐心解答，我明白了。
感谢！！！
